#!/usr/bin/env bash

curl -s https://api.coindesk.com/v1/bpi/currentprice/usd.json | 
jq -r '[.time|.updated],[.bpi|.USD|.rate],[.bpi|.USD|.rate_float]' |
xargs >> /$HOME/.cache/daily.btc.pricecheck 
