#!/bin/sh

#while read -r file 

      fullpath="pwd/*"
      case "$1" in 
        "w")
     notify-send -i $HOME/Pictures/wallpaper/cbebop.jpeg "zipping" ; 
                 zip -r -D -@ -q * && 
                notify-send -i $HOME/Pictures/wallpaper/cbebop.jpeg "done"|                mv *.zip Kings.Viking.cbz &&  mv *.cbz ../ 
esac

