#!/bin/sh

#while read -r file 

      fullpath="pwd/*"
      case "$1" in 
        "w")
     notify-send "zipping" ; 
                 zip -r -D -@ -q * && 
                notify-send "done"|
                mv *.zip Kings.Viking.cbz &&  mv *.cbz ../ 
esac

