#!/bin/sh
### Work in progress
#while read -r file 

      fullpath="pwd/*"
      case "$1" in 
        "w")
     notify-send "zipping" ; 
                 zip -r -D -@ -q * && 
                notify-send "done"|
                mv *.zip file.cbz &&  mv *.cbz ../ 
esac

